import datetime

# This format list generated by chat.openai.com
KNOWN_TIMESTAMP_FORMATS = [
    "%d/%b/%Y:%H:%M:%S %z",             # Apache CLF: 20/Jan/2020:21:32:14 -0700
    "%Y-%m-%dT%H:%M:%S.%fZ",            # ISO 8601 with microseconds + Zulu (UTC)
    "%Y-%m-%dT%H:%M:%SZ",               # ISO 8601 without microseconds
    "%Y-%m-%d %H:%M:%S",                # Common syslog-ish format
    "%b %d %H:%M:%S",                   # Syslog: Jan 20 21:32:14 (year not included)
    "%Y-%m-%dT%H:%M:%S%z",              # ISO 8601 with timezone
    "%d-%b-%Y %H:%M:%S",                # 20-Jan-2020 21:32:14
    "%m/%d/%Y %H:%M:%S",                # 01/20/2020 21:32:14
]

def parse_datetime_to_iso_format(datetime_str):
    for format in KNOWN_TIMESTAMP_FORMATS:
        try:
            if format == "%b %d %H:%M:%S":
                datetime_str = datetime_str.replace(year=datetime.now().year)
            return datetime.strptime(datetime_str, format).isoformat()
        except:
            continue
    raise ValueError(f"The given datetime {datetime_str} doesn't match any of the supported formats")